runltp: Fix print default scenario list for -N parameter
+ cleanup formatting a bit

Signed-off-by: Petr Vorel <pvorel@suse.cz>

diff --git a/runltp b/runltp
--- a/runltp
+++ b/runltp
@@ -596,51 +596,32 @@ main()
 
     # If user does not provide a command file select a default set of testcases
     # to execute.
-    if [ -z "$CMDFILES" ] && [ -z "$CMDFILEADDR" ]
-    then
-        cat <<-EOF >&1
+    if [ -z "$CMDFILES" ] && [ -z "$CMDFILEADDR" ]; then
 
-    INFO: no command files were provided. Will execute the following
-          runtest scenario files:
-
-`cat $LTPROOT/scenario_groups/default | tr '\012' ' '`
-
-	EOF
-
-	SCENARIO_LISTS="$LTPROOT/scenario_groups/default"
+        SCENARIO_LISTS="$LTPROOT/scenario_groups/default"
         if [ "$RUN_NETEST" -eq 1 ]; then
             SCENARIO_LISTS="$SCENARIO_LISTS $LTPROOT/scenario_groups/network"
         fi
 
-    # DO NOT INDENT/DEDENT!
-        if [ -n "$SCENARIO_LISTS" ]; then
-            # Insurance to make sure that the first element in the pipe
-            # completed successfully.
-            cat_ok_sentinel=$TMP/cat_ok.$$
-	    (cat $SCENARIO_LISTS && touch "$cat_ok_sentinel") | \
-                while read scenfile; do
+        cat <<-EOF >&1
+INFO: no command files were provided. Executing following runtest scenario files:
+`cat $SCENARIO_LISTS | tr '\012' ' '`
 
-                    scenfile=${LTPROOT}/runtest/$scenfile
+EOF
+        cat_ok_sentinel=$TMP/cat_ok.$$
+        touch "$cat_ok_sentinel"
+        cat $SCENARIO_LISTS | while read scenfile; do
+            scenfile=${LTPROOT}/runtest/$scenfile
+            [ -f "$scenfile" ] || continue
 
-                    # Skip over non-existent scenario files; things are
-                    # robust enough now that the build will fail if these
-                    # files don't exist.
-                    [ -f "$scenfile" ] || continue
-
-                    cat $scenfile >> "$TMP/alltests" || {
-                        echo "FATAL: unable to append to command file"
-                        rm -Rf "$TMP"
-                        rm -f "$cat_ok_sentinel"
-                        exit 1
-                    }
-
-                done
-
-            rm -f "$cat_ok_sentinel"
-
-        fi
-    # ^^DO NOT INDENT/DEDENT!^^
-
+            cat $scenfile >> "$TMP/alltests" || {
+                echo "FATAL: unable to append to command file"
+                rm -Rf "$TMP"
+                rm -f "$cat_ok_sentinel"
+                exit 1
+            }
+        done
+        rm -f "$cat_ok_sentinel"
     fi
 
     [ -n "$CMDFILES" ] && \
