1. Please see README.mk-devel for a full description of the changes from a Make perspective. 2. Several files were changed to accomodate correct installation practices, most notably ones in testcases/network/{ipv6,tcp_cmds}, testcases/kernel/sched/hyperthreading/ht_enabled/..., and some items in tools/..., and also to avoid collisions as far as installed testcases (scripts, compiled C apps) were concerned. 3. Several apps weren't autoconf safe and some autoconf tests and conditional statements have been placed in sourcecode and in Makefiles to either a) prevent the tests from being built / installed or b) turn the tests into dummy apps which print out TCONF messages due to lack-of-build support.
Signed-off-by: Garrett Cooper <yanegomi@gmail.com>

diff --git a/testcases/commands/cron/cron02 b/testcases/commands/cron/cron02
--- a/testcases/commands/cron/cron02
+++ b/testcases/commands/cron/cron02
@@ -54,10 +54,13 @@ do_setup(){
 
 	# restart cron daemon
 	# Red Hat uses crond, SuSE/Other uses cron.
-	if [ -f /etc/init.d/crond ]; then
+	if [ -x /etc/init.d/crond ]; then
 		/etc/init.d/crond restart
-	else
+	elif [ -x /etc/init.d/cron ]; then
 		/etc/init.d/cron restart
+	else
+		echo "Could not determine cron init.d script."
+		exit 1
 	fi
 }
 
diff --git a/testcases/network/tcp_cmds/ftp/ftp03 b/testcases/network/tcp_cmds/ftp/ftp03
--- a/testcases/network/tcp_cmds/ftp/ftp03
+++ b/testcases/network/tcp_cmds/ftp/ftp03
@@ -31,69 +31,66 @@
 #	This version is intended for EAL certification, it will need modification 
 #	to conform with LTP standards in the offical LTP tree.
 
-RHOST="localhost"
-TEST_USER="ftpuser1"
-TEST_USER_PASSWD="eal"
-TEST_USER_ENCRYPTED_PASSWD="42VmxaOByKwlA"
-TEST_USER_HOMEDIR="/home/$TEST_USER"
-tvar=${MACHTYPE%-*}
-tvar=${tvar#*-}
-
-if [ $tvar = "redhat" -o $tvar = "redhat-linux" ] 
-then
-ls /etc/vsftpd/vsftpd.conf
- if [ $? != 0 ]
-      then { 
-         echo "vsftpd.conf not found.  Possible cause: does not exist on WS."
-         echo "Test ftp03 FAIL."
-         EXIT_CODE=1
-         exit 1
-      } 
- fi
-LOCAL_ENABLE=`cat /etc/vsftpd/vsftpd.conf | grep "^local_enable=" | awk -F= '{print $2}'`
-else
-LOCAL_ENABLE=`cat /etc/vsftpd.conf | grep "^local_enable=" | awk -F= '{print $2}'`
-fi
-if [ "$LOCAL_ENABLE" != "YES" ]; then
-  LOCAL_ENABLE="NO"
-fi 
-
-EXIT_CODE=0
-
 #-----------------------------------------------------------------------
 # FUNCTION:  do_setup
 #-----------------------------------------------------------------------
 
-do_setup(){
+do_setup()
+{
 	
-	#erase user if he may exist , so we can have a clean env
-        rm -rf /home/$TEST_USER
-	userdel $TEST_USER
-        sleep 1
+    RHOST="localhost"
+    TCtmp=/home/$TEST_USER
+    TEST_USER="ftpuser1"
+    TEST_USER_PASSWD="eal"
+    TEST_USER_ENCRYPTED_PASSWD="42VmxaOByKwlA"
+    TEST_USER_HOMEDIR="/home/$TEST_USER"
+    VSFTP_CONF=
 
-	useradd -m -p $TEST_USER_ENCRYPTED_PASSWD $TEST_USER 
-	if [ $? != 0 ] 
-	then { 
-		echo "Could not add test user $TEST_USER on system $RHOST."
-		exit 1
-	}
-	fi
+    tst_setup
 
-	#create users home diretory (SLES 8 does not do this, even when specified in adduser)
-	USER_UID=`id -u $TEST_USER`
-	USER_GID=`id -g $TEST_USER`
-	mkdir $TEST_USER_HOMEDIR
-	chown -R $USER_UID.$USER_GID $TEST_USER_HOMEDIR
-	
+    exists ftp useradd userdel vftpd
+
+    for vsftp_conf in /etc/vsftpd /etc; do
+
+        if [ -r "$vsftp_confdir/vsftp.conf" ]; then
+            VSFTP_CONF="$vsftp_confdir/vsftp.conf"
+            break
+        fi
+
+    done
+    if [ ! -r "$VSFTP_CONF" ] ; then
+        end_testcase "vsftpd.conf not found."
+    fi
+    LOCAL_ENABLE=$(awk -F= '/^local_enable=/ {print $2}' "$VSFTP_CONF")
+
+    [ "$LOCAL_ENABLE" != "YES" ] && LOCAL_ENABLE="NO"
+
+    userdel $TEST_USER
+    sleep 1
+
+    if ! useradd -m -p $TEST_USER_ENCRYPTED_PASSWD $TEST_USER; then 
+        end_testcase "Could not add test user $TEST_USER on system $RHOST."
+    fi
+
+    trap do_cleanup QUIT
+
+    # create users home diretory (SLES 8 does not do this, even when specified
+    # in adduser)
+    USER_UID=$(id -u $TEST_USER)
+    USER_GID=$(id -g $TEST_USER)
+    mkdir -p "$TEST_USER_HOMEDIR"
+    chown -R $USER_UID:$USER_GID $TEST_USER_HOMEDIR
+
 }
 
 #-----------------------------------------------------------------------
 # FUNCTION:  do_cleanup
 #-----------------------------------------------------------------------
 
-do_cleanup(){
-        rm -rf /home/$TEST_USER
-	userdel $TEST_USER
+do_cleanup()
+{
+    userdel $TEST_USER
+    tst_cleanup
 }
 
 #-----------------------------------------------------------------------
@@ -105,51 +102,48 @@ do_cleanup(){
 #-----------------------------------------------------------------------
 
 do_test(){
-	echo "TEST: Ftp into a remote host as a local user (other than root), LOCAL_ENABLE=$LOCAL_ENABLE"
+    tst_resm TINFO "TEST: Ftp into a remote host as a local user (other than root), LOCAL_ENABLE=$LOCAL_ENABLE"
 
-if [ "$LOCAL_ENABLE" = "YES" ]; then {
+    if [ "$LOCAL_ENABLE" = "YES" ]; then
 	expect -c "
-                   spawn ftp $RHOST
-                   sleep 1
-                   expect -re \": \"
-                   send \"$TEST_USER\r\"
-                   expect -re \"Password:\"
-                   send \"$TEST_USER_PASSWD\r\"
-                   expect {
-                     # 530 - Login failed
-                           \"530\" {send_user \"==> TEST \#$TEST : FAIL (ftp rejected login attempt)\n\";exit 1}
-                     # 230 - Login successful
-                           \"230\" {send_user \"==> TEST \#$TEST : PASS (ftp allowed login attempt)\n\";exit 0}
-                   }
-                   expect \"ftp> \"
-                   send \"quit\r\"
+            spawn ftp $RHOST
+            sleep 1
+            expect -re \": \"
+            send \"$TEST_USER\r\"
+            expect -re \"Password:\"
+            send \"$TEST_USER_PASSWD\r\"
+            expect {
+                # 530 - Login failed
+                \"530\" {send_user \"==> TEST \#$TEST : FAIL (ftp rejected login attempt)\n\";exit 1}
+                # 230 - Login successful
+                \"230\" {send_user \"==> TEST \#$TEST : PASS (ftp allowed login attempt)\n\";exit 0}
+            }
+            expect \"ftp> \"
+            send \"quit\r\"
 	"
-} else {
+    else
         expect -c "
-                   spawn ftp $RHOST
-                   sleep 1
-                   expect -re \": \"
-                   send \"$TEST_USER\r\"
-                   expect -re \"Password:\"
-                   send \"$TEST_USER_PASSWD\r\"
-                   expect {
-                     # 230 - Login successful
-                           \"230\" {send_user \"==> TEST \#$TEST : FAIL (ftp allowed login attempt)\n\";exit 1} 
-                     # 500 - Login failed
-                           \"500\" {send_user \"==> TEST \#$TEST : PASS (ftp rejected login attempt)\n\";exit 0}
-                     # 530 - Login failed
-                           \"530\" {send_user \"==> TEST \#$TEST : PASS (ftp rejected login attempt)\n\";exit 0}
-                   }
-                   expect \"ftp> \"
-                   send \"quit\r\"
+            spawn ftp $RHOST
+            sleep 1
+            expect -re \": \"
+            send \"$TEST_USER\r\"
+            expect -re \"Password:\"
+            send \"$TEST_USER_PASSWD\r\"
+            expect {
+                # 230 - Login successful
+                \"230\" {send_user \"==> TEST \#$TEST : FAIL (ftp allowed login attempt)\n\";exit 1} 
+                # 500 - Login failed
+                \"500\" {send_user \"==> TEST \#$TEST : PASS (ftp rejected login attempt)\n\";exit 0}
+                # 530 - Login failed
+                \"530\" {send_user \"==> TEST \#$TEST : PASS (ftp rejected login attempt)\n\";exit 0}
+            }
+            expect \"ftp> \"
+            send \"quit\r\"
         "
-} fi
+    fi
 
-
-    if [ $? != 0 ]
-        then {
-        EXIT_CODE=1 
-        }
+    if [ $? != 0 ]; then
+        end_testcase "Testcase failed"
     fi
 }	
 
@@ -158,7 +152,9 @@ if [ "$LOCAL_ENABLE" = "YES" ]; then {
 # PURPOSE:  To invoke the functions to perform the tasks described in
 #           the prologue.
 #----------------------------------------------------------------------
+. net_cmdlib.sh
+
+read_opts $*
 do_setup
 do_test
-do_cleanup
-exit $EXIT_CODE
+end_testcase
diff --git a/testcases/network/tcp_cmds/ftp/ftp04 b/testcases/network/tcp_cmds/ftp/ftp04
--- a/testcases/network/tcp_cmds/ftp/ftp04
+++ b/testcases/network/tcp_cmds/ftp/ftp04
@@ -28,97 +28,77 @@
 #   03/04/03 Jerone Young (jeroney@us.ibm.com)
 #   09/21/05 Kris Wilson (krisw@us.ibm.com) Check if vsftpd is on system.
 
-
-RHOST=localhost
-TEST_USER=root
-
-if [ $PASSWD ]
-then
-	TEST_USER_PASSWORD=$PASSWD
-else	
-	echo "YOU MUST EXPORT PASSWD VARIABLE"
-	exit 1
-fi
-
-
-EXIT_CODE=0
-
 #-----------------------------------------------------------------------
-# FUNCTION:  verify_user_is_in_ftpusers_db
+# FUNCTION:  do_setup
 #-----------------------------------------------------------------------
                                                                                
-verify_user_is_in_ftpusers_db(){
+do_setup()
+{
 
-tvar=${MACHTYPE%-*}
-tvar=${tvar#*-}
+    tvar=${MACHTYPE%-*}
+    tvar=${tvar#*-}
 
-       if [ $tvar = "redhat" -o $tvar = "redhat-linux" ] 
-       then
-         # Check if vsftpd is on system.
-         which vsftpd
-         if [ $? != 0 ]
-         then { 
-            echo "vsftpd not found.  Possible cause: does not exist on WS."
-            echo "Test ftp04 FAIL."
-            EXIT_CODE=1
-            exit 1
-       } 
-       fi
+    RHOST=localhost
+    TEST_USER=root
+
+    tst_setup
+
+    if [ -n "$PASSWD" ]; then
+        TEST_USER_PASSWORD=$PASSWD
+    else	
+        end_testcase "You must set your password via the PASSWD variable."
+        exit 1
+    fi
+
+    exists awk expect ftp vsftpd
+
+    if [ $tvar = "redhat" -o $tvar = "redhat-linux" ]; then
         echo "Verifying test user $TEST_USER is in /etc/vsftpd.ftpusers database..."
-        FTPUSERS=`grep $TEST_USER /etc/vsftpd.ftpusers`
-       else
+        FTPUSERS=$(awk "/$TEST_USER/" /etc/vsftpd.ftpusers)
+    else
         echo "Verifying test user $TEST_USER is in /etc/ftpusers database..."
-        FTPUSERS=`grep $TEST_USER /etc/ftpusers`
-       fi
-        if [ "x$FTPUSERS" = "x" ]
-        then {
-            echo "Test user $TEST_USER not found in /etc/ftpusers unable to run TEST, exiting 0 ..."
-			exit 0
-         }
-		 fi
-	
+        FTPUSERS=$(awk "/$TEST_USER/" /etc/ftpusers)
+    fi
+    if [ -z "$FTPUSERS" ] ; then
+        end_testcase "Test user $TEST_USER not found in /etc/ftpusers unable to run TEST, exiting 0 ..."
+    fi
+
 }
 
 #-----------------------------------------------------------------------
 # FUNCTION:  do_test
 #-----------------------------------------------------------------------
-do_test() {
+do_test()
+{
 
-		echo "TEST: Ftp should reject $TEST_USER from loging in successfully"
-        expect -c "
-                   spawn ftp $RHOST
-                   sleep 1
-                   expect -re \": \"
-                   send \"$TEST_USER\r\"
-                   expect -re \"Password:\"
-                   send \"$TEST_USER_PASSWD\r\"
-                   expect {
-                     # 230 - Login successful
-                           \"230\" {send_user \"==> TEST \#$TEST : FAIL (ftp allowed login attempt)\n\";exit 1}
-                     # 530 - Login failed
-                           \"530\" {send_user \"==> TEST \#$TEST : PASS (ftp rejected login attempt)\n\";exit 0}
-                   }
-                   expect \"ftp> \"
-                   send \"quit\r\"
-        "
-
-    if [ $? != 0 ]
-        then {
-        EXIT_CODE=1
+    tst_resm TINFO "Ftp should reject $TEST_USER from loging in successfully"
+    expect -c "
+        spawn ftp $RHOST
+        sleep 1
+        expect -re \": \"
+        send \"$TEST_USER\r\"
+        expect -re \"Password:\"
+        send \"$TEST_USER_PASSWD\r\"
+        expect {
+            # 230 - Login successful
+            \"230\" {send_user \"==> TEST \#$TEST : FAIL (ftp allowed login attempt)\n\";exit 1}
+            # 530 - Login failed
+            \"530\" {send_user \"==> TEST \#$TEST : PASS (ftp rejected login attempt)\n\";exit 0}
         }
-    fi
+        expect \"ftp> \"
+        send \"quit\r\"
+    "
+
+    [ $? -eq 0 ] || end_testcase "Testcase failed."
 
 }
 
 #----------------------------------------------------------------------
 # FUNCTION: MAIN
 #----------------------------------------------------------------------
-verify_user_is_in_ftpusers_db
+. net_cmdlib.sh
+
+read_opts $*
+do_setup
 do_test
-exit $EXIT_CODE
-
-
-
-
-
-
+end_testcase
diff --git a/testcases/network/tcp_cmds/ftp/ftp05 b/testcases/network/tcp_cmds/ftp/ftp05
--- a/testcases/network/tcp_cmds/ftp/ftp05
+++ b/testcases/network/tcp_cmds/ftp/ftp05
@@ -31,90 +31,85 @@
 #	This version is intended for EAL certification, it will need modification 
 #	to conform with LTP standards in the offical LTP tree.
 
-RHOST="localhost"
-TEST_USER="anonymous"
-TEST_USER_PASSWD="noone@nowhere.com"
+do_setup()
+{
+    RHOST="localhost"
+    TEST_USER="anonymous"
+    TEST_USER_PASSWD="noone@nowhere.com"
+    VSFTP_CONF=
 
-tvar=${MACHTYPE%-*}
-tvar=${tvar#*-}
+    tst_setup
 
-if [ $tvar = "redhat" -o $tvar = "redhat-linux" ] 
-then
+    exists expect ftp vsftpd
 
-   # Check if vsftpd is on system.
-   which vsftpd
-   if [ $? != 0 ]
-   then {
-      echo "vsftpd not found.  Possible cause: does not exist on WS."
-      echo "Test ftp05 FAIL."
-      EXIT_CODE=1
-      exit 1
-   }
-   fi
+    for vsftp_conf in /etc/vsftpd /etc; do
 
-ANONYMOUS_ENABLE=`cat /etc/vsftpd/vsftpd.conf | grep "^anonymous_enable=" | awk -F= '{print $2}'`
-else
-ANONYMOUS_ENABLE=`cat /etc/vsftpd.conf | grep "^anonymous_enable=" | awk -F= '{print $2}'`
-fi
-if [ "$ANONYMOUS_ENABLE" != "NO" ]; then
-  ANONYMOUS_ENABLE="YES"
-fi 
+        if [ -r "$vsftp_confdir/vsftp.conf" ]; then
+            VSFTP_CONF="$vsftp_confdir/vsftp.conf"
+            break
+        fi
 
-EXIT_CODE=0
-
-#-----------------------------------------------------------------------
-# FUNCTION:  do_test
-#
-# DESCRIPTION: The anonymous user will ftp in and create a directory in his home directory on the remote host.
-#-----------------------------------------------------------------------
-
-do_test(){
-	echo "TEST: Ftp into a remote host as anonymous user, ANONYMOUS_ENABLE=$ANONYMOUS_ENABLE"
-
-if [ "$ANONYMOUS_ENABLE" = "YES" ]; then {
-	expect -c "
-                   spawn ftp $RHOST
-                   sleep 1
-                   expect -re \": \"
-                   send \"$TEST_USER\r\"
-                   expect -re \"Password:\"
-                   send \"$TEST_USER_PASSWD\r\"
-                   expect {
-                     # 530 - Login failed
-                           \"530\" {send_user \"==> TEST \#$TEST : FAIL (ftp rejected login attempt)\n\";exit 1}
-                     # 230 - Login successful
-                           \"230\" {send_user \"==> TEST \#$TEST : PASS (ftp allowed login attempt)\n\";exit 0}
-                   }
-                   expect \"ftp> \"
-                   send \"quit\r\"
-	"
-} else {
-        expect -c "
-                   spawn ftp $RHOST
-                   sleep 1
-                   expect -re \": \"
-                   send \"$TEST_USER\r\"
-                   expect -re \"Password:\"
-                   send \"$TEST_USER_PASSWD\r\"
-                   expect {
-                     # 230 - Login successful
-                           \"230\" {send_user \"==> TEST \#$TEST : FAIL (ftp allowed login attempt)\n\";exit 1} 
-                     # 500 - Login failed
-                           \"500\" {send_user \"==> TEST \#$TEST : PASS (ftp rejected login attempt)\n\";exit 0}
-                     # 530 - Login failed
-                           \"530\" {send_user \"==> TEST \#$TEST : PASS (ftp rejected login attempt)\n\";exit 0}
-                   }
-                   expect \"ftp> \"
-                   send \"quit\r\"
-        "
-} fi
-
-
-    if [ $? != 0 ]
-        then {
-        EXIT_CODE=1 
-        }
+    done
+    if [ ! -r "$VSFTP_CONF" ] ; then
+        end_testcase "vsftpd.conf not found."
     fi
+    ANONYMOUS_ENABLE=$(awk -F= '/^anonymous_enable=/ {print $2}' "$VSFTP_CONF")
+    if [ "$ANONYMOUS_ENABLE" != "NO" ]; then
+        ANONYMOUS_ENABLE="YES"
+    fi
+}
+
+#-----------------------------------------------------------------------
+# FUNCTION   : do_test
+#
+# DESCRIPTION: The anonymous user will ftp in and create a directory in his/her
+#              home directory on the remote host.
+#-----------------------------------------------------------------------
+
+do_test()
+{
+    tst_resm TINFO "Ftp into a remote host as anonymous user; ANONYMOUS_ENABLE=$ANONYMOUS_ENABLE"
+
+    if [ "$ANONYMOUS_ENABLE" = "YES" ]; then
+        expect -c "
+            spawn ftp $RHOST
+            sleep 1
+            expect -re \": \"
+            send \"$TEST_USER\r\"
+            expect -re \"Password:\"
+            send \"$TEST_USER_PASSWD\r\"
+            expect {
+                # 530 - Login failed
+                \"530\" {send_user \"==> TEST \#$TEST : FAIL (ftp rejected login attempt)\n\";exit 1}
+                # 230 - Login successful
+                \"230\" {send_user \"==> TEST \#$TEST : PASS (ftp allowed login attempt)\n\";exit 0}
+            }
+            expect \"ftp> \"
+            send \"quit\r\"
+	"
+    else
+        expect -c "
+            spawn ftp $RHOST
+            sleep 1
+            expect -re \": \"
+            send \"$TEST_USER\r\"
+            expect -re \"Password:\"
+            send \"$TEST_USER_PASSWD\r\"
+            expect {
+                # 230 - Login successful
+                \"230\" {send_user \"==> TEST \#$TEST : FAIL (ftp allowed login attempt)\n\";exit 1} 
+                # 500 - Login failed
+                \"500\" {send_user \"==> TEST \#$TEST : PASS (ftp rejected login attempt)\n\";exit 0}
+                # 530 - Login failed
+                \"530\" {send_user \"==> TEST \#$TEST : PASS (ftp rejected login attempt)\n\";exit 0}
+            }
+            expect \"ftp> \"
+            send \"quit\r\"
+        "
+    fi
+
+    [ $? -eq 0 ] || end_testcase "Testcase failed."
+
 }	
 
 #----------------------------------------------------------------------
@@ -122,5 +117,9 @@ if [ "$ANONYMOUS_ENABLE" = "YES" ]; then {
 # PURPOSE:  To invoke the functions to perform the tasks described in
 #           the prologue.
 #----------------------------------------------------------------------
+. net_cmdlib.sh
+
+read_opts $*
+do_setup
 do_test
-exit $EXIT_CODE
+end_testcase
diff --git a/testcases/network/tcp_cmds/rsh/rsh01 b/testcases/network/tcp_cmds/rsh/rsh01
--- a/testcases/network/tcp_cmds/rsh/rsh01
+++ b/testcases/network/tcp_cmds/rsh/rsh01
@@ -33,32 +33,22 @@
 #
 #
 #----------------------------------------------------------------------
-#Uncomment line below for debug output.
-#trace_logic=${trace_logic:-"set -x"}
-$trace_logic
 
-RHOST=${RHOST:-`hostname`}
-SLEEPTIME=${SLEEPTIME:-0}
-NUMLOOPS=${NUMLOOPS:-25}
-
-
-#-----------------------------------------------------------------------
-#
-# FUNCTION:  exists
-#
-#-----------------------------------------------------------------------
-
-exists()
+do_setup()
 {
-   for cmd in $1
-   do
-       which $cmd 2>&1 1>/dev/null
-	   if [ $? -ne 0 ]
-	   then
-	       tst_resm TBROK "Test broke: command $cmd not found"
-		   exit 1
-       fi
-   done
+
+    FAIL_IMMEDIATELY=${FAIL_IMMEDIATELY:-1}
+    SLEEPTIME=${SLEEPTIME:-0}
+    NUMLOOPS=${NUMLOOPS:-1}
+
+    export TST_TOTAL=$NUMLOOPS
+
+    tst_setup
+
+    exists awk hostname rsh
+
+    RHOST=${RHOST:-`hostname`}
+
 }
 
 #-----------------------------------------------------------------------
@@ -69,40 +59,44 @@ exists()
 
 do_test()
 {
-   $trace_logic
 
-   COUNT=1
-   while [ $COUNT -le $NUMLOOPS ]
-   do
-      CHECK=$(rsh -n -l root $RHOST "ls -l /etc/hosts | wc -w")
+    while [ $TST_COUNT -le $NUMLOOPS ]; do
 
-      if [ "$CHECK" -eq 9 ]; then 
-         tst_resm TINFO "rsh Test successful in loop $COUNT"
-      else
-         tst_resm TBROK "FAILED: rsh failed"
-      fi
-      sleep $SLEEPTIME
-      COUNT=$(( $COUNT + 1 ))
-   done
-}
+        PASSED=0
 
-#=============================================================================
-# FUNCTION NAME:        end_testcase
-#
-# FUNCTION DESCRIPADDRTION: Clean up
-#
-# PARAMETERS:           string, IF AND ONLY IF the testcase fails
-#
-# RETURNS:              None.
-#=============================================================================
+        if OUT=$(rsh -n -l root $RHOST 'ls -l /etc/hosts'); then 
 
-end_testcase()
-{
-   $trace_logic
+            #
+            # Successful output would be something of the form:
+            #
+            # gcooper@orangebox ~ $ ls -l /etc/hosts         
+            # -rw-r--r-- 1 root root 463 Jul  5 09:26 /etc/hosts
+            #
+            echo "$OUT" | \
+                awk 'NF == 9 && $NF == "/etc/hosts" { exit 0 } END { exit 1 }' \
+                >& /dev/null
 
-   [ $# -eq 0 ] && { tst_resm TPASS "Test Successful"; exit 0; }
-   tst_resm TFAIL "Test Failed: $@"
-   exit 1
+            if [ $? -eq 0 ] ; then
+                tst_resm TPASS "rsh to $RHOST test succeeded"
+                PASSED=1
+            fi
+
+        fi
+
+        if [ $PASSED -ne 1 ] ; then
+            tst_resm TFAIL "rsh to $RHOST failed"
+            # If the first rsh failed, the likelihood that the rest will
+            # succeed is low.
+            if [ "$FAIL_IMMEDIATELY" = "1" ] && [ $COUNT -eq 1 ]; then
+                exit 2
+            fi
+        fi
+
+        sleep $SLEEPTIME
+        incr_tst_count
+
+    done
+
 }
 
 #----------------------------------------------------------------------
@@ -113,9 +107,9 @@ end_testcase()
 # OUTPUT:   A testcase run log with the results of the execution of this
 #           test.
 #----------------------------------------------------------------------
-export TCID=rsh01
-export TST_TOTAL=1
-export TST_COUNT=1
-exists "rsh wc"
+. net_cmdlib.sh
+
+read_opts $*
+do_setup
 do_test
 end_testcase
diff --git a/testcases/network/tcp_cmds/rwho/rwho01 b/testcases/network/tcp_cmds/rwho/rwho01
--- a/testcases/network/tcp_cmds/rwho/rwho01
+++ b/testcases/network/tcp_cmds/rwho/rwho01
@@ -38,44 +38,9 @@
 #
 #==============================================================================
 # error codes:  0 rwho/ruptime successful
-# 	        1 rwho failed no local and remote host in file
-# 	        2 ruptime failed no local and remote host in file
+#             1 rwho failed no local and remote host in file
+#             2 ruptime failed no local and remote host in file
 #==============================================================================
-#Uncomment line below for debug output.
-#trace_logic=${trace_logic:-"set -x"}
-$trace_logic
-
-LHOST=`hostname | cut -f1 -d.`
-RHOST=${RHOST:-$LHOST}
-TC=rwho
-TCtmp=${TCtmp:-/tmp/$TC}
-CLEANUP=${CLEANUP:-ON}
-
-PID=0
-RHOST_PID=0
-SLEEPTIME=${SLEEPTIME:-20}
-NUMLOOPS=${NUMLOOPS:-25}
-OUTFILE=${OUTFILE:-$TCtmp/rwho.out}
-
-#-----------------------------------------------------------------------
-#
-# FUNCTION:  exists
-#
-#-----------------------------------------------------------------------
-
-exists()
-{
-   for cmd in $1
-   do
-       which $cmd 2>&1 1>/dev/null
-	   if [ $? -ne 0 ]
-	   then
-	       tst_resm TBROK "Test broke: command $cmd not found"
-		   exit 1
-       fi
-   done
-}
-
 
 #-----------------------------------------------------------------------
 #
@@ -85,44 +50,49 @@ exists()
 
 do_setup()
 {
-   $trace_logic
 
-   export TCID=rwho01
-   export TST_TOTAL=1
-   export TST_COUNT=1
+    TCtmp=${TCtmp:-$LTPROOT/testcases/bin/$TC${EXEC_SUFFIX}$$}
 
-   exists "rwho rsh killall grep awk cut"
+    PID=0
+    RHOST_PID=0
+    SLEEPTIME=${SLEEPTIME:-20}
+    NUMLOOPS=${NUMLOOPS:-25}
+    OUTFILE=${OUTFILE:-$TCtmp/${TC}.out}
 
-   ps -ef | grep rwhod | grep -v grep 
-   if [ $? -ne 0 ]; then
-      tst_resm TINFO "Starting rwhod on $LHOST"
-      /usr/sbin/rwhod  
-      [ $? -eq 0 ] || end_testcase "Unable to start rwhod on $LHOST"
-      PID=1
-      sleep $SLEEPTIME
-   fi
+    tst_setup
 
-   rsh -n -l root $RHOST ps -ef | grep rwhod
-   if [ $? -ne 0 ]; then
-      tst_resm TINFO "Starting rwhod on $RHOST"
-      rsh -n -l root $RHOST /usr/sbin/rwhod
-      if [ $? -ne 0 ]; then
-	  end_testcase "Unable to start rwhod on $RHOST"
-      fi
-      RHOST_PID=$(rsh -n -l root $RHOST ps -ef | grep rwhod | grep -v grep | awk '{print $2 ; exit}')
-      if [ -z "$RHOST_PID" ]; then
-	  RHOST_PID=0
-	  end_testcase "Unable to start rwhod on $RHOST"
-      fi
-      sleep $SLEEPTIME
-   fi
+    exists awk cut hostname killall ps rsh rwho
 
-   RHOSTNAME=`rsh -n -l root $RHOST hostname | cut -f1 -d.`
-   if [ -z "$RHOSTNAME" ]; then
-       end_testcase "Unable to determine RHOSTNAME"
-   fi
+    LHOST=`hostname | cut -f1 -d.`
+    RHOST=${RHOST:-$LHOST}
 
-   mkdir -p $TCtmp
+    trap do_cleanup EXIT
+
+    if ! ps -ef | awk '/rwhod/ && $0 !~ /awk/'; then
+        tst_resm TINFO "Starting rwhod on $LHOST"
+        rwhod || end_testcase "Unable to start rwhod on $LHOST"
+        PID=1
+        sleep $SLEEPTIME
+    fi
+
+    if ! rsh -n -l root $RHOST ps -ef | awk '/rwhod/ && $0 !~ /awk/'; then
+        tst_resm TINFO "Starting rwhod on $RHOST"
+        if ! rsh -n -l root $RHOST /usr/sbin/rwhod; then
+            end_testcase "Unable to start rwhod on $RHOST"
+        fi
+        RHOST_PID=$(rsh -n -l root $RHOST ps -ef | awk '/rwhod/ && $0 !~ /awk/ {print $2 ; exit}')
+        if [ -z "$RHOST_PID" ]; then
+            RHOST_PID=0
+            end_testcase "Unable to start rwhod on $RHOST"
+        fi
+        sleep $SLEEPTIME
+    fi
+
+    RHOSTNAME=`rsh -n -l root $RHOST hostname | cut -f1 -d.`
+    if [ -z "$RHOSTNAME" ]; then
+        end_testcase "Unable to determine RHOSTNAME"
+    fi
+
 }
 
 #-----------------------------------------------------------------------
@@ -133,26 +103,23 @@ do_setup()
 
 do_test()
 {
-   $trace_logic
 
-   COUNT=1
-   while [ $COUNT -le $NUMLOOPS ]
-   do
-      rwho -a > $OUTFILE
-      HOST=`awk '{print $2}' $OUTFILE|grep "$LHOST\>"|cut -f1 -d:|sort -u`
-      [ "$HOST" = "$LHOST" ] || end_testcase "$LHOST is not in rwho outfile"
-      HOST=`awk '{print $2}' $OUTFILE|grep "$RHOSTNAME\>"|cut -f1 -d:|sort -u`
-      [ "$HOST" = "$RHOSTNAME" ] || end_testcase "$RHOSTNAME is not in rwho outfile"
+    while [ $TST_COUNT -le $NUMLOOPS ]; do
+        rwho -a > $OUTFILE
+        HOST=`awk "\$2 ~ /$LHOST>/" $OUTFILE | cut -f1 -d: | sort -u`
+        [ "$HOST" = "$LHOST" ] || end_testcase "$LHOST is not in rwho outfile"
+        HOST=`awk "\$2 ~ /$RHOSTNAME>/" $OUTFILE | cut -f1 -d: | sort -u`
+        [ "$HOST" = "$RHOSTNAME" ] || end_testcase "$RHOSTNAME is not in rwho outfile"
 
-      ruptime -a > $OUTFILE
-      HOST=`awk '{print $1}' $OUTFILE|grep "$LHOST\>"|sort -u`
-      [ "$HOST" = "$LHOST" ] || end_testcase "$LHOST is not in ruptime outfile"
-      HOST=`awk '{print $1}' $OUTFILE|grep "$RHOSTNAME\>"|sort -u`
-      [ "$HOST" = "$RHOSTNAME" ] || end_testcase "$RHOSTNAME is not in ruptime outfile"
+        ruptime -a > $OUTFILE
+        HOST=`awk "\$1 ~ /$LHOST>/" $OUTFILE | sort -u`
+        [ "$HOST" = "$LHOST" ] || end_testcase "$LHOST is not in ruptime outfile"
+        HOST=`awk "\$1 ~ /$RHOSTNAME>/" $OUTFILE | sort -u`
+        [ "$HOST" = "$RHOSTNAME" ] || end_testcase "$RHOSTNAME is not in ruptime outfile"
 
-      tst_resm TINFO "Test $COUNT of $NUMLOOPS complete"
-      COUNT=$(( $COUNT + 1 ))
-   done
+        tst_resm TINFO "Test $COUNT of $NUMLOOPS complete"
+        incr_tst_count
+    done
 }
 
 #-----------------------------------------------------------------------
@@ -163,38 +130,18 @@ do_test()
 
 do_cleanup()
 {
- rm -fr $TCtmp
- if [ $PID -ne 0 ]; then
-    tst_resm TINFO "Stopping rwhod on $LHOST"
-    killall rwhod 
- fi
+    if [ $PID -ne 0 ]; then
+        tst_resm TINFO "Stopping rwhod on $LHOST"
+        killall rwhod 
+    fi
 
- if [ $RHOST_PID -ne 0 ]; then
-    tst_resm TINFO "Stopping rwhod on $RHOST"
-    rsh -n -l root $RHOST "killall rwhod"
- fi
-}
- 
-#=============================================================================
-# FUNCTION NAME:        end_testcase
-#
-# FUNCTION DESCRIPTION: Clean up
-#
-# PARAMETERS:           string, IF AND ONLY IF the testcase fails
-#
-# RETURNS:              None.
-#=============================================================================
+    if [ $RHOST_PID -ne 0 ]; then
+        tst_resm TINFO "Stopping rwhod on $RHOST"
+        rsh -n -l root $RHOST "killall rwhod"
+    fi
 
-end_testcase()
-{
-   $trace_logic
-   
-   if [ $CLEANUP = "ON" ]; then
-     do_cleanup
-   fi
-   [ $# -eq 0 ] && { tst_resm TPASS "Test Successful"; exit 0; }
-   tst_resm TFAIL "Test Failed: $@"
-   exit 1
+    tst_cleanup
+
 }
 
 #-----------------------------------------------------------------------
@@ -202,6 +149,9 @@ end_testcase()
 # FUNCTION:  MAIN
 #
 #-----------------------------------------------------------------------
+. net_cmdlib.sh
+
+read_opts $*
 do_setup
 do_test
 end_testcase
diff --git a/testcases/network/tcp_cmds/ssh/ssh01 b/testcases/network/tcp_cmds/ssh/ssh01
--- a/testcases/network/tcp_cmds/ssh/ssh01
+++ b/testcases/network/tcp_cmds/ssh/ssh01
@@ -26,36 +26,43 @@
 #    03/03 Jerone Young (jeroney@us.ibm.com)
 #
 
-export RHOST="localhost"
-export TEST_USER="ssh_usr1"
-export TEST_USER_PASSWD="eal"
-export TEST_USER_ENCRYPTED_PASSWD="42VmxaOByKwlA"
-export TEST_USER_HOMEDIR="/home/$TEST_USER"
-
 #-----------------------------------------------------------------------
 # FUNCTION:  do_setup
 #-----------------------------------------------------------------------
 
-do_setup(){
-	
-	#erase user if he may exist , so we can have a clean env
-        rm -rf /home/$TEST_USER
-        userdel $TEST_USER
-        sleep 1
+do_setup()
+{
 
-        useradd -m -p $TEST_USER_ENCRYPTED_PASSWD $TEST_USER 
-        if [ $? != 0 ]
-        then {
-                echo "Could not add test user $TEST_USER to system $RHOST."
-                exit 1
-        }
-        fi
+    export RHOST="localhost"
+    export TEST_USER="ssh_usr1"
+    export TEST_USER_PASSWD="eal"
+    export TEST_USER_ENCRYPTED_PASSWD="42VmxaOByKwlA"
+    export TEST_USER_HOMEDIR="/home/$TEST_USER"
 
-	#create users home diretory (SLES 8 does not do this, even when specified in adduser)
-        USER_UID=`id -u $TEST_USER`
-        USER_GID=`id -g $TEST_USER`
-        mkdir $TEST_USER_HOMEDIR
-        chown -R $USER_UID.$USER_GID $TEST_USER_HOMEDIR
+    #erase user if he may exist , so we can have a clean env
+    TCtmp=/home/$TEST_USER
+
+    tst_setup
+
+    exists expect ssh ssh01_s1 useradd userdel
+
+    userdel $TEST_USER
+    sleep 1
+
+    if ! useradd -m -p $TEST_USER_ENCRYPTED_PASSWD $TEST_USER; then
+        end_testcase "Could not add test user $TEST_USER to system $RHOST."
+    fi
+
+    # create users home diretory (SLES 8 does not do this, even when specified
+    # in adduser)
+    USER_UID=$(id -u $TEST_USER)
+    USER_GID=$(id -g $TEST_USER)
+    if ! mkdir "$TEST_USER_HOMEDIR"; then
+        end_testcase "Failed to create $TEST_USER_HOMEDIR"
+    fi
+    chown -Rf $USER_UID.$USER_GID "$TEST_USER_HOMEDIR"
+
+    trap do_cleanup EXIT
 
 }
 
@@ -64,20 +71,21 @@ do_setup(){
 #-----------------------------------------------------------------------
 
 do_cleanup(){
-        rm -rf /home/$TEST_USER
-        userdel $TEST_USER 
+    userdel $TEST_USER
+    tst_cleanup
 }
 
 #-----------------------------------------------------------------------
 # FUNCTION:  MAIN
 #
 # DESCRIPTION: Create Test User
-#              Call upon script to make sure test user cannont log in with invalid password
-#              Cleanup Test User from system
-#              Exit with exit code of script called upon
+#          Call upon script to make sure test user cannont log in with invalid password
+#          Cleanup Test User from system
+#          Exit with exit code of script called upon
 #-----------------------------------------------------------------------
+. net_cmdlib.sh
+
+read_opts $*
 do_setup
-ssh01_s1
-EXIT_CODE=$?
+ssh01_s1 || end_testcase "Testcase failed"
 do_cleanup
-exit $EXIT_CODE
diff --git a/testcases/network/tcp_cmds/ssh/ssh02 b/testcases/network/tcp_cmds/ssh/ssh02
--- a/testcases/network/tcp_cmds/ssh/ssh02
+++ b/testcases/network/tcp_cmds/ssh/ssh02
@@ -26,57 +26,69 @@
 #    03/03 Jerone Young (jeroney@us.ibm.com)
 #
 
-export RHOST="localhost"
-export TEST_USER="ssh_usr2"
-export TEST_USER_PASSWD="now_this_is_a_good_ltp_test_password"
-export TEST_USER_ENCRYPTED_PASSWD="42VmxaOByKwlA"
-export TEST_USER_HOMEDIR="/home/$TEST_USER"
-
 #-----------------------------------------------------------------------
 # FUNCTION:  do_setup
 #-----------------------------------------------------------------------
 
-do_setup(){
-	#erase user if he may exist , so we can have a clean env
-        rm -rf /home/$TEST_USER
-        userdel $TEST_USER 
-        sleep 1
-	
-        useradd -m -p $TEST_USER_ENCRYPTED_PASSWD $TEST_USER 
-        if [ $? != 0 ]
-        then {
-                echo "Could not add test user $TEST_USER to system $RHOST."
-                exit 1
-        }
-        fi
-	
-	#create users home diretory (SLES 8 does not do this, even when specified in adduser)
-        USER_UID=`id -u $TEST_USER`
-        USER_GID=`id -g $TEST_USER`
-        mkdir $TEST_USER_HOMEDIR
-        chown -R $USER_UID.$USER_GID $TEST_USER_HOMEDIR
-	
+do_setup()
+{
+
+    export RHOST="localhost"
+    export TEST_USER="ssh_usr2"
+    export TEST_USER_PASSWD="now_this_is_a_good_ltp_test_password"
+    export TEST_USER_ENCRYPTED_PASSWD="42VmxaOByKwlA"
+    export TEST_USER_HOMEDIR="/home/$TEST_USER"
+
+    # erase user if he/she already exists, so we can have a clean env
+    TCtmp=/home/$TEST_USER
+
+    rm -Rf $TCtmp
+
+    tst_setup
+
+    exists expect ssh ssh02_s1 useradd userdel
+
+    userdel $TEST_USER 
+    sleep 1
+
+    if ! useradd -m -p $TEST_USER_ENCRYPTED_PASSWD $TEST_USER; then
+        end_testcase "Could not add test user $TEST_USER to system $RHOST."
+    fi
+
+    # create users home diretory (SLES 8 does not do this, even when specified
+    # in adduser)
+    USER_UID=$(id -u $TEST_USER)
+    USER_GID=$(id -g $TEST_USER)
+    if ! mkdir "$TEST_USER_HOMEDIR"; then
+        end_testcase "Failed to create $TEST_USER_HOMEDIR"
+    fi
+    chown -R $USER_UID.$USER_GID "$TEST_USER_HOMEDIR"
+
+    trap do_cleanup EXIT
+
 }
 
 #-----------------------------------------------------------------------
 # FUNCTION:  do_cleanup
 #-----------------------------------------------------------------------
 
-do_cleanup(){
-        rm -rf /home/$TEST_USER
-        userdel $TEST_USER
+do_cleanup()
+{
+    userdel $TEST_USER
+    tst_cleanup
 }
 
 #-----------------------------------------------------------------------
 # FUNCTION:  MAIN
 #
 # DESCRIPTION: Create Test User
-#              Call upon script to make sure an invalid user can not have access 
-#              Cleanup Test User from system
-#              Exit with exit code of script called upon
+#          Call upon script to make sure an invalid user can not have access 
+#          Cleanup Test User from system
+#          Exit with exit code of script called upon
 #-----------------------------------------------------------------------
+. net_cmdlib.sh
+
+read_opts $*
 do_setup
-ssh02_s1
-EXIT_CODE=$?
+ssh02_s1 || end_testcase "Testcase failed"
 do_cleanup
-exit $EXIT_CODE
