This is a Fix for Bug 21134 with SLES 10.  Now the syslog tests will test syslog-ng or syslogd depending on which one is present.  The update was made for syslog01 - syslog10.

diff --git a/testcases/kernel/syscalls/syslog/syslog07 b/testcases/kernel/syscalls/syslog/syslog07
--- a/testcases/kernel/syscalls/syslog/syslog07
+++ b/testcases/kernel/syscalls/syslog/syslog07
@@ -19,38 +19,53 @@
 # 12/05/02  Port to bash -Robbie Williamson <robbiew@us.ibm.com>
 # 02/05/03  Modified - Manoj Iyer <manjo@mail.utexas.edu> use USCTEST macros
 #           fixed bugs.
-
+# 07/26/05  Michael Reed  <mreedltp@vnet.ibm.com>
+#           Made changes to account for the replacement of syslogd 
+#           with syslog-ng
+#
 ##################################################################
 # case 7: Test the priorities....                                #
 #                                                                #
 #         o Add lowest prority level i.e debug level entry to    #
-#           configuration file.                                  #
+#           configuration file.                                  #    
+#           o For syslog-ng the priority is set to all           #
+#             because of the format of syslog-ng.conf            #
+#             The format of the tests is the same, all levels of #
+#             debug and above are logged                         #
 #         o Send syslog messages at all levels and see whether   #
 #           higher level messages are logged.                    #
 ##################################################################
 DEBIAN=0
 #number of seconds to wait for another syslog test to complete
 wait_count=60
+#configuration file for syslog or syslog-ng
+CONFIG_FILE=""
+
+#Command for syslog or syslog-ng
+syslog_cmd=""
 
 cleanup()
 {
-if [ $status_flag -eq 0 ]
-then
-	tst_resm TPASS "higher level messages are logged."
-else
-	tst_resm TFAIL "higher level messages are not logged."
-fi
+
+  if [ $status_flag -eq 0 ]
+  then
+	tst_resm TPASS "$explaination level messages are logged."
+  else
+	tst_resm TFAIL "$explaination level messages are not logged."
+  fi
 
 #Restore syslog.conf
-mv /etc/syslog.conf.ltpbak /etc/syslog.conf
+  mv $CONFIG_FILE.ltpback $CONFIG_FILE
 
 #Restart syslog
-tst_resm TINFO "Restart syslog"
-/etc/init.d/syslog restart 2>&1 1>/dev/null 
-sleep 2
-if [ $DEBIAN -eq 1 ];then
- rm -f /etc/init.d/syslog
-fi
+  tst_resm TINFO "restart syslog"
+  $syslog_cmd restart 2>&1 1>/dev/null
+
+
+  sleep 2
+  if [ $DEBIAN -eq 1 ];then
+     rm -f /etc/init.d/syslog
+  fi
 
 exit $status_flag
 }
@@ -70,18 +85,58 @@ syslog_case7()
 
 	# check if syslogd command exits.
 	echo
-	# check if syslogd command exits. Check for both syslogd & syslogd-ng in SLES10
-	if [ -z $(which syslogd) ]
+
+   #check to see if syslogd or syslog-ng exists
+	if [ -e /sbin/syslogd  ]
 	then
-	if [ -z $(which syslog-ng) ]
-	then 
-		tst_resm TBROK "syslogd or syslog-ng  no such command"
-		status_flag=1
-		cleanup
+	    CONFIG_FILE="/etc/syslog.conf"
+	    syslog_cmd="/etc/init.d/syslog"
+	    tst_resm TINFO "o Add lowest prority level i.e debug level entry to" 
+            tst_resm TINFO "  configuration file."
+	elif [ -e /sbin/syslog-ng ]
+        then
+	    tst_resm TINFO "o Ensure all priority levels can be logged"
+	    CONFIG_FILE="/etc/syslog-ng/syslog-ng.conf"
+            syslog_cmd="syslog-ng"
+	else
+	    tst_resm TBROK "syslogd or syslog-ng  no such command"
+	    status_flag=1
+	    cleanup	
 	fi
-	else 
-		echo "Running tests"
-	fi
+
+# Adds some clarification of log message when syslog-ng is used
+        if [ $CONFIG_FILE == /etc/syslog.conf ]; then
+           explaination="Higher"
+        else
+           explaination="All"
+        fi
+
+
+tst_resm TINFO " o Send syslog messages at all levels and see whether"
+tst_resm TINFO "   $explaination level messages are logged."
+
+
+
+#Back up configuration file
+if [ ! -e $CONFIG_FILE ]
+then
+	tst_resm TBROK  "$CONFIG_FILE not found!"
+else
+#Pause if another LTP syslog test is running
+      while [ -e $CONFIG_FILE.ltpback ]  
+      do
+          if [ $(( wait_count-- )) -gt 0 ]
+          then
+            sleep 1
+          else
+	    tst_resm TBROK "Another syslog test appears to be stuck, could not run"
+            status_flag=1
+	    exit $status_flag
+           fi
+        done
+        cp $CONFIG_FILE $CONFIG_FILE.ltpback
+fi
+         echo "Running tests"
 
 	#Create symlink to /etc/init.d/sysklogd for Debian
         find /etc/init.d/ |grep sysklogd 2>&1 1>/dev/null 
@@ -105,23 +160,32 @@ syslog_case7()
 
 
 	# Create the configuration file specific to this test case.
-	echo "user.debug        /var/log/messages" > /etc/syslog.conf
+        if [ $CONFIG_FILE == "/etc/syslog.conf" ]; then
+	   echo "user.debug        /var/log/messages" > /etc/syslog.conf
+        else
+           echo "source src{ internal(); unix-dgram("/dev/log"); \ 
+                 udp(ip("0.0.0.0") port(514)); };" > $CONFIG_FILE 
+           echo " " >> $CONFIG_FILE
+           echo " " >> $CONFIG_FILE
+           echo "# Added for syslog testcase"  >> $CONFIG_FILE
+           echo "filter f_syslog_messages {facility(user); };"  >> $CONFIG_FILE
+           echo "destination syslog-messages { file("/var/log/messages");};" \
+                 >> $CONFIG_FILE
+           echo "log { source(src); filter(f_syslog_messages); \
+                 destination(syslog-messages); };" >> $CONFIG_FILE
+   fi
 
-	#Restart syslog
-	tst_resm TINFO "Restart syslog"
-	/etc/init.d/syslog restart 2>&1 1>/dev/null 
+
+if [ $CONFIG_FILE == "/etc/syslog.conf" ]; then
+       #Restart syslog
+       $syslog_cmd restart 2>&1 1>/dev/null
+else
+         #re-start syslog-ng
+         $syslog_cmd restart 2>&1 1>/dev/null	
+fi
 	sleep 2
 
-	# Grep for the following patterns in the log file...
-	# check if /var/log/maillog script exists
-	find /var/log/ |grep maillog 2>&1 1>/dev/null 
-	RC=$?
-	if [ $RC -ne 0 ]
-	then
-		tst_resm TBROK "/var/log/maillog no such log file"
-		status_flag=1
-		cleanup
-	fi
+       if [ -e /var/log/messages ]; then
 	emerg_old=`grep -c "syslogtst: emergency log" /var/log/messages`
 	alert_old=`grep -c "syslogtst: alert log" /var/log/messages`
 	crit_old=`grep -c "syslogtst: critical log" /var/log/messages`
@@ -130,6 +194,17 @@ syslog_case7()
 	notice_old=`grep -c "syslogtst: notice log" /var/log/messages`
 	info_old=`grep -c "syslogtst: info log" /var/log/messages`
 	debug_old=`grep -c "syslogtst: debug log" /var/log/messages`
+else
+	emerg_old=0
+	alert_old=0
+	crit_old=0
+	err_old=0
+	notice_old=0
+	warning_old=0
+	notice_old=0
+	info_old=0
+	debug_old=0
+fi 
 
 	# Call syslogtst. It will send the messages of all levels.
 	syslogtst 7 2>/dev/null
@@ -140,14 +215,15 @@ syslog_case7()
 	sleep 2
 
 	# check if /var/log/maillog script exists
-	find /var/log/ |grep maillog 2>&1 1>/dev/null 
-	RC=$?
-	if [ $RC -ne 0 ]
-	then
-		tst_resm TBROK "/var/log/maillog no such log file"
-		status_flag=1
-		cleanup
-	fi
+#	find /var/log/ |grep maillog 2>&1 1>/dev/null 
+#	RC=$?
+#	if [ $RC -ne 0 ]
+#	then
+#		tst_resm TBROK "/var/log/maillog no such log file"
+#		status_flag=1
+#		cleanup
+#	fi
+
 	emerg_new=`grep -c "syslogtst: emergency log" /var/log/messages`
 	alert_new=`grep -c "syslogtst: alert log" /var/log/messages`
 	crit_new=`grep -c "syslogtst: critical log" /var/log/messages`
@@ -184,31 +260,9 @@ fi
 RC=0
 status_flag=0
 
+
 tst_resm TINFO " Test the priorities"
-tst_resm TINFO " o Add lowest prority level i.e debug level entry to"
-tst_resm TINFO "   configuration file."
-tst_resm TINFO " o Send syslog messages at all levels and see whether"
-tst_resm TINFO "   higher level messages are logged."
 
-#Back up /etc/syslog.conf
-if ! [ -a /etc/syslog.conf ]
-then
-        tst_resm TBROK "/etc/syslog.conf not found!"
-else
-    while [ -a /etc/syslog.conf.ltpbak ]  #Pause if another LTP syslog test is running
-    do
-        if [ $(( wait_count-- )) -gt 0 ]
-        then
-          sleep 1
-        else
-          tst_resm TBROK "Another syslog test appears to be stuck, could not run"
-          status_flag=1
-          exit $status_flag
-        fi
-
-    done
-    cp /etc/syslog.conf /etc/syslog.conf.ltpbak
-fi
 
 
 syslog_case7
