Apply the rest of the needed cleanup:
1. Add needed variables for tst_resm(1) to function.
2. Fix indentation.

Signed-off-by: Garrett Cooper <yanegomi@gmail.com>

diff --git a/testcases/commands/at/at_allow01 b/testcases/commands/at/at_allow01
--- a/testcases/commands/at/at_allow01
+++ b/testcases/commands/at/at_allow01
@@ -24,9 +24,12 @@
 #   run cron jobs.
 #
 #   HISTORY:
-#           04/03 Jerone Young (jyoung5@us.ibm.com)
+#		   04/03 Jerone Young (jyoung5@us.ibm.com)
 #
 
+export TCID=at_allow01
+export TST_TOTAL=1
+export TST_COUNT=1
 TMP=${TMP:=/tmp}
 allow="/etc/at.allow"
 test_user1="test_user_1"
@@ -41,38 +44,38 @@ tmpfile="$TMP/at_allow_test"
 
 do_setup()
 {
-    # Move any files that may get in the way.
-    rm "${tmpfile}" >/dev/null 2>&1
-    mv "${allow}" "${allow}.old" >/dev/null 2>&1
+	# Move any files that may get in the way.
+	rm "${tmpfile}" >/dev/null 2>&1
+	mv "${allow}" "${allow}.old" >/dev/null 2>&1
 
-    # Remove users for clean enviroment.
-    rm -rf "${test_user1_home}" "${test_user2_home}"
-    userdel -r "${test_user1}" >/dev/null 2>&1
-    userdel -r "${test_user2}" >/dev/null 2>&1
+	# Remove users for clean enviroment.
+	rm -rf "${test_user1_home}" "${test_user2_home}"
+	userdel -r "${test_user1}" >/dev/null 2>&1
+	userdel -r "${test_user2}" >/dev/null 2>&1
 
-    # Create the 1st user.
-    if ! useradd -g users -d "${test_user1_home}"  -m "${test_user1}"; then
-	echo "Could not add test user ${test_user1} to system."
-	exit 1
-    fi
+	# Create the 1st user.
+	if ! useradd -g users -d "${test_user1_home}"  -m "${test_user1}"; then
+		echo "Could not add test user ${test_user1} to system."
+		exit 1
+	fi
 
-    # Create the 2nd user.
-    if ! useradd -g users -d "${test_user2_home}" -m "${test_user2}"; then
-	echo "Could not add test user ${test_user2} to system."
-	exit 1
-    fi
+	# Create the 2nd user.
+	if ! useradd -g users -d "${test_user2_home}" -m "${test_user2}"; then
+		echo "Could not add test user ${test_user2} to system."
+		exit 1
+	fi
 
-    # This is the workaround for a potential bug.
-    # [Bug 468337] At Refuse to Work with Non-login Shell
-    # https://bugzilla.redhat.com/show_bug.cgi?id=468337
-    # As we are running in non-login shell now, we cannot run the script
-    # by simply given it a relative path. Therefore, we copy it to test
-    # users' home directories, and run it from there.
-    cp "$0" "${test_user1_home}"
-    cp "$0" "${test_user2_home}"
+	# This is the workaround for a potential bug.
+	# [Bug 468337] At Refuse to Work with Non-login Shell
+	# https://bugzilla.redhat.com/show_bug.cgi?id=468337
+	# As we are running in non-login shell now, we cannot run the script
+	# by simply given it a relative path. Therefore, we copy it to test
+	# users' home directories, and run it from there.
+	cp "$0" "${test_user1_home}/."
+	cp "$0" "${test_user2_home}/."
 
-    # Restart atd daemon.
-    /etc/init.d/atd restart
+	# Restart atd daemon.
+	/etc/init.d/atd restart
 }
 
 #-----------------------------------------------------------------------
@@ -80,14 +83,14 @@ do_setup()
 #-----------------------------------------------------------------------
 do_cleanup()
 {
-    # We forcefully remove those files anyway. Otherwise userdel may
-    # give us bad warnings.
-    rm -rf "${test_user1_home}" "${test_user2_home}"
-    userdel -r "${test_user1}" >/dev/null 2>&1
-    userdel -r "${test_user2}" >/dev/null 2>&1
-    rm "${allow}"
-    mv "${allow}.old" "${allow}" >/dev/null 2>&1
-    rm "${tmpfile}" >/dev/null 2>&1
+	# We forcefully remove those files anyway. Otherwise userdel may
+	# give us bad warnings.
+	rm -rf "${test_user1_home}" "${test_user2_home}"
+	userdel -r "${test_user1}" >/dev/null 2>&1
+	userdel -r "${test_user2}" >/dev/null 2>&1
+	rm "${allow}"
+	mv "${allow}.old" "${allow}" >/dev/null 2>&1
+	rm "${tmpfile}" >/dev/null 2>&1
 }
 
 #-----------------------------------------------------------------------
@@ -95,77 +98,75 @@ do_cleanup()
 #-----------------------------------------------------------------------
 run_test()
 {
-    if [ $(whoami) = "${test_user1}" ]; then 
-        echo "TEST: $allow should allow only those who in the file to\
- run jobs."
-        echo "(1) TEST THAT PERSON IN ${allow} IS ABLE TO RUN JOB."
-	echo "echo 'TEST JOB RAN' >>\"${tmpfile}\" 2>&1" |
-         at -m now + 1 minutes
-        if [ $? != 0 ]; then
-            echo "Error while adding job using at for user ${test_user1}."
-            exit 1
-        fi
-        echo " Sleeping for 75 seconds...."	
-        sleep 75
+	if [ $(whoami) = "${test_user1}" ]; then 
+		echo "TEST: $allow should allow only those who in the file to run jobs."
+		echo "(1) TEST THAT PERSON IN ${allow} IS ABLE TO RUN JOB."
+		echo "echo 'TEST JOB RAN' >>\"${tmpfile}\" 2>&1" |
+		if ! at -m now + 1 minutes ; then
+			echo "Error while adding job using at for user ${test_user1}."
+			exit 1
+		fi
+		echo " Sleeping for 75 seconds...."	
+		sleep 75
 
-        exit_code=1
-        test -e "${tmpfile}" && exit_code=0
-        if [ ${exit_code} -eq 1 ]; then
-            echo "At did not allow user to execute job, TEST FAILED."
+		exit_code=1
+		test -e "${tmpfile}" && exit_code=0
+		if [ ${exit_code} -eq 1 ]; then
+			tst_resm TFAIL "At did not allow user to execute job"
 	else
-            echo "At allowed user to execute test job, TEST PASSED."
+			tst_resm TPASS "At allowed user to execute test job"
 	fi
 
 	rm -f "${tmpfile}" >/dev/null 2>&1
-        exit ${exit_code}
+		exit ${exit_code}
 
-    elif [ $(whoami) = "${test_user2}" ]; then
-        echo "(2) TEST PERSON THAT IS NOT IN ${allow} IS NOT ABLE TO\
- RUN JOB."
-        echo "echo 'TEST JOB RAN' >>\"${tmpfile}\" 2>&1" |
-         at -m now + 1 minutes
-        if [ $? != 0 ]; then
-            echo "Expected error while adding job user at for user\
- ${test_user2}"
-        fi
+	elif [ $(whoami) = "${test_user2}" ]; then
+		echo "(2) TEST PERSON THAT IS NOT IN ${allow} IS NOT ABLE TO RUN JOB."
+		echo "echo 'TEST JOB RAN' >>\"${tmpfile}\" 2>&1" |
+		if ! at -m now + 1 minutes; then
+			echo "Expected error while adding job user at for user ${test_user2}"
+		fi
 	echo "Sleeping for 75 seconds...."
-        sleep 75
+		sleep 75
 
-        exit_code=1
-        test -e "${tmpfile}" || exit_code=0
-        if [ ${exit_code} -eq 1 ]; then
-            echo "At allowed user to execute test job, TEST FAILED."
-        else
-            echo "At did not allow user to execute job, TEST PASSED."
-        fi
+		exit_code=1
+		test -e "${tmpfile}" || exit_code=0
+		if [ ${exit_code} -eq 1 ]; then
+			tst_resm TFAIL "At allowed user to execute test job"
+		else
+			tst_resm TPASS "At did not allow user to execute job"
+		fi
 
-        rm -f "${tmpfile}" >/dev/null 2>&1
-	exit ${exit_code}
-    fi
+		rm -f "${tmpfile}" >/dev/null 2>&1
+		exit ${exit_code}
+	fi
 }
 
 #-----------------------------------------------------------------------
 # FUNCTION: main
 #-----------------------------------------------------------------------
 if type at > /dev/null; then
-    tst_resm TCONF "at command not found on system"
+	tst_resm TCONF "at command not found on system"
 elif [ "$(id -ru)" = 0 ]; then
-    do_setup
-    echo "${test_user1}" >"${allow}"
-    exit_code=0
-    
-    su "${test_user1}" -lc "${test_user1_home}/$(basename $0)"
-    if [ $? != 0 ]; then
-	exit_code=1
-    fi
-    
-    su "${test_user2}" -lc "${test_user2_home}/$(basename $0)"
-    if [ $? != 0 ]; then
-	exit_code=1
-    fi 
-    do_cleanup
-    exit ${exit_code}
+	if do_setup; then
+
+		if ! echo "${test_user1}" >"${allow}"; then
+			exit_code=1
+		elif ! su "${test_user1}" -lc "${test_user1_home}/${0##*/}"; then
+			exit_code=1
+		elif ! su "${test_user2}" -lc "${test_user2_home}/${0##*/}"; then
+			exit_code=1
+		else
+			exit_code=0
+		fi 
+
+		do_cleanup
+
+	else
+		exit_code=1
+	fi
+	exit ${exit_code}
 else
-    run_test
-    exit 0
+	run_test
+	exit 0
 fi
