Keep on working on fixing the selinux-testsuite...
Signed-off-by: Garrett Cooper <yanegomi@gmail.com>

diff --git a/testcases/kernel/security/selinux-testsuite/refpolicy/Makefile.selinux b/testcases/kernel/security/selinux-testsuite/refpolicy/Makefile.selinux
--- a/testcases/kernel/security/selinux-testsuite/refpolicy/Makefile.selinux
+++ b/testcases/kernel/security/selinux-testsuite/refpolicy/Makefile.selinux
@@ -1,7 +1,7 @@
 #
-#    kernel/security/selinux-testsuite/policy Makefile
+#    kernel/security/selinux-testsuite/refpolicy selinux install Makefile
 #
-#    Copyright (C) 2009, Cisco Systems Inc.
+#    Copyright (C) 2010, Cisco Systems Inc.
 #
 #    This program is free software; you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -17,16 +17,24 @@
 #    with this program; if not, write to the Free Software Foundation, Inc.,
 #    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
-# Garrett Cooper, August 2009
+# Garrett Cooper, January 2010
 #
 
-top_srcdir		?= ../../../../..
+POLICY_DEVEL_DIR	?= $(DESTDIR)/usr/share/selinux/devel
+SEMODULE		?= $(DESTDIR)/usr/sbin/semodule
 
-include	$(top_srcdir)/include/mk/env_pre.mk
+.PHONY: cleanup load
+cleanup:
+	-$(SEMODULE) -r test_policy
+	$(RM) -f $(POLICY_DEVEL_DIR)/test_policy.* test_policy.te
 
-INSTALL_DIR		:= testcases/kernel/security/selinux-testsuite/policy
-
-INSTALL_TARGETS		:= Makefile.selinux
-
-include $(top_srcdir)/include/mk/generic_leaf_target.mk
-include $(abs_srcdir)/Makefile.selinux
+load:
+	@set -e; if [ -d "$(POLICY_DEVEL_DIR)" ]; then \
+	    cp -p test_policy.* $(POLICY_DEVEL_DIR); \
+	    $(MAKE) -C $(POLICY_DEVEL_DIR) clean; \
+	    $(MAKE) -C $(POLICY_DEVEL_DIR) test_policy.pp; \
+	    $(SEMODULE) -i $(POLICY_DEVEL_DIR)/test_policy.pp; \
+	else \
+            echo "ERROR: You must have selinux-policy?-devel? installed."; \
+	    false; \
+	fi
