Applied patches from Bryce Harrington to allow NFSv4 testing: I noticed that while LTP has tests for NFS, they all work only against NFS versions 2 and 3.  The Linux NFSv4 project is working to improve testing of the new version 4 of NFS, and it would be extremely helpful to have NFSv4 testing supported by LTP.  I have implemented the changes needed to add this capability to ltp-full-20050608 in the following 7 patches.  If this patchset is acceptable to the LTP team, I'd like to see it added to the LTP testsuite.
The changes performed by these patches include:

1.  Adds a "-t $NFS_TYPE" parameter to each test's mount command, to
    allow passing in of 'nfs' or 'nfs4'.  NFSv4 mounts are created via
    the -t flag instead of the '-o vers=N' flag.

2.  Conditionalizes the mount options.  For NFSv4, we do not need to
    specify proto= or vers= options, so if $NFS_TYPE is defined as
    'nfsv4', these options are not set.

3.  $TESTDIR conformance.  Each of the NFS tests was creating and naming
    its exported/mounted test directory slightly differently.  These
    patches make the NFS tests use consistent naming approaches, and to
    use a configurable variable $TESTDIR instead of hardcoding through
    the script.

4.  NFSv4 export logic.  In NFSv4, exported directories are placed into
    a "pseudofilesystem", rather than being individual exports.  This
    requires slightly different logic in each test case to establish the
    $TESTDIR export directory.

5.  Removed some extraneous 'sleep 5' statements.

6.  Fixed an error message regarding export failure.  It was reporting
    "Could export...", but should say, "Could not export."

7.  More consistent use of 'mkdir -p $TESTDIR' instead of just 'mkdir
    $TESTDIR'.  This will ensure that any intermediate path elements get
    made as well.

8.  Minor changes.  Spelling fixes, location of PID=$$ moved higher,
    change test of $# to $? (was causing incorrect failures).

Each patch implements the above changes to a different test case.




Unresolved Issues
-----------------
(1) There are still some inconsistencies between the various test cases
    but this is fairly cosmetic, and not really related to NFSv4 so I
    left them as is.

(2) Only one of the test cases actually emits a PASS/FAIL, so this is a
    fairly important inconsistency with normal LTP style.  I may submit
    a patch to fix this later if I have time.

(3) I did not make any modifications to cthon04 or nfs_fstress; they
    appear to be implemented differently than the other test cases, and
    they do not appear to get invoked by testscripts/networktests.sh

(4) nfslock01 is also left unmodified.  This one is called by
    testscripts/networktests.sh, but does not appear to export or mount
    anything, so I could not tell how this could be modified for NFSv4.


Thanks,
Bryce

diff --git a/testcases/network/nfs/nfs01/nfs01 b/testcases/network/nfs/nfs01/nfs01
--- a/testcases/network/nfs/nfs01/nfs01
+++ b/testcases/network/nfs/nfs01/nfs01
@@ -70,10 +70,14 @@ setup_testcase()
 {
 $trace_logic
    
+    PID=$$
+
     VERSION=${VERSION:=2}
     RHOST=${RHOST:=`hostname`}
     NFILES=${NFILES:=1000}
     SOCKET_TYPE=${SOCKET_TYPE:=udp}
+    TESTDIR=${TESTDIR:=/tmp/$TC$PID.testdir}
+    NFS_TYPE=${NFS_TYPE:=nfs}
 
     echo ""
     echo "Test Options:"
@@ -81,25 +85,39 @@ $trace_logic
     echo " RHOST: $RHOST"
     echo " NFILES: $NFILES"
     echo " SOCKET_TYPE: $SOCKET_TYPE"
-    sleep 5
+    echo " NFS_TYPE: $NFS_TYPE"
+    echo " TESTDIR: $TESTDIR"
 
-    PID=$$
-    OPTS=${OPTS:=",vers=$VERSION "}
-    REMOTE_DIR=${RHOST}:/tmp/nfs01$PID.testdir
+    if [ "x$NFS_TYPE" != "xnfs4" ]; then
+        OPTS=${OPTS:="-o proto=$SOCKET_TYPE,vers=$VERSION "}
+    fi
+
+    REMOTE_DIR=${RHOST}:${TESTDIR}
     LOCAL_DIR=$TCtmp/${RHOST}.${LUSER}
     LUSER=${LUSER:=root}
     mkdir -p $TCtmp || end_testcase "Could not create $TCtmp"
     chmod 777 $TCtmp
 
     echo "Setting up remote machine: $RHOST"
-    rsh -n $RHOST "mkdir /tmp/nfs01$PID.testdir"
+    rsh -n $RHOST "mkdir -p $TESTDIR"
     [ $? = 0 ] || end_testcase "Could not create remote directory"
-    rsh -n $RHOST "/usr/sbin/exportfs -i -o no_root_squash,rw *:/tmp/nfs01$PID.testdir"
-    [ $? = 0 ] || end_testcase "Could export remote directory"
 
-    echo "Mounting NFS filesystem $REMOTE_DIR on $TCtmp with parameters $SOCKET_TYPE$OPTS"
-    mount -o proto=$SOCKET_TYPE$OPTS $REMOTE_DIR $TCtmp || end_testcase "Cannot mount $TCtmp"
+    if [ "x$NFS_TYPE" == "xnfs4" ]; then
+        rsh -n $RHOST "mkdir -p /export$TESTDIR"
+        [ $? = 0 ] || end_testcase "Could not create /export$TESTDIR on server"
+        rsh -n $RHOST "mount --bind $TESTDIR /export$TESTDIR"
+        [ $? = 0 ] || end_testcase "Could not bind $TESTDIR to export on server"
+        rsh -n $RHOST "/usr/sbin/exportfs -o no_root_squash,rw,nohide,insecure,no_subtree_check *:$TESTDIR"
+        [ $? = 0 ] || end_testcase "Could not export remote directory"
+    else
+        rsh -n $RHOST "/usr/sbin/exportfs -i -o no_root_squash,rw *:$TESTDIR"
+        [ $? = 0 ] || end_testcase "Could not export remote directory"
+    fi
+
+    echo "Mounting NFS filesystem $REMOTE_DIR on $TCtmp with options '$OPTS'"
+    mount -t $NFS_TYPE $OPTS $REMOTE_DIR $TCtmp || end_testcase "Cannot mount $TCtmp"
     [ $? = 0 ] || end_testcase "Could not mount $REMOTE_DIR"
+
     cd $TCtmp 
     echo "Removing old and create new directories"
     [ -d $LOCAL_DIR ] && rm -rf $LOCAL_DIR
@@ -161,12 +179,12 @@ $trace_logic
 	
 	echo "Cleaning up testcase"
 
-        mount -o proto=$SOCKET_TYPE$OPTS $REMOTE_DIR $TCtmp || echo "Cannot mount $TCtmp"
+        mount -t $NFS_TYPE $OPTS $REMOTE_DIR $TCtmp || echo "Cannot mount $TCtmp"
 	rm -rf $LOCAL_DIR || echo "Cannot remove $LOCAL_DIR"
         /bin/umount $TCtmp || echo "Cannot umount $TCtmp"
 	rm -rf $TCtmp || echo "Cannot remove $TCtmp"
-        rsh -n $RHOST "/usr/sbin/exportfs -u *:/tmp/nfs01$PID.testdir"
-	rsh -n $RHOST "rm -rf /tmp/nfs01$PID.testdir"
+        rsh -n $RHOST "/usr/sbin/exportfs -u *:$TESTDIR"
+		 rsh -n $RHOST "rm -rf $TESTDIR"
     fi
 
     [ $# = 0 ] && { echo "Test Successful"; exit 0; }
